### ISSUE TITLE
Is there away to order children nodes in the order of ports of source node connected

### ISSUE THREAD

**Issue by pranithasri** [kieler/elkjs#163]

**Comment by soerendomroes** [comment]
This can be achieved easily if the initial order induces a crossing minimal graph (see [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQMYQB2AzjAXgLIR0gDyUdUAdFXFMHDjBZ0ABQBKAUQBiEsQH0JAEQDiEgMpoA9JrTQ0AORaL1cgIL7FClerS8stiGhwAPAA54YSHBThlKNDkZmNg5OUigIKhoKMABhCABXHzx9JhwASQoAMxAE71IcdAAGTiKARi0dehgwBDg0BBwQVzQYLN12PEI0KghcuBhKVqo0Cgh68MjosDQkGApPUD9qWgY01k6uSaj5uMTkqBFoOEycvIoC4tKK7TRq2vrG5tb26A5u3v7BimHR8bRttNZvNFiASEQxnRRmUiIQwDhoWgALQAPlGACZYQR4YjUaMAMxYnEUCp4igAFiJCJJyLRFAArCRIdT0WgAN5ENBcjDAABGTTQACIKOjBUQAL5MtIE9mc7mYfkgIUUfFiyUQ6UU2XcnmK5XktVSqEM7XyvkC4X0tVAA) and [here](https://www.researchgate.net/publication/358262575_Preserving_Order_during_Crossing_Minimization_in_Sugiyama_Layouts) for details and limitations).

**Comment by soerendomroes** [comment]
No, this is not possible since it is a different algorithm.

**Comment by soerendomroes** [comment]
What features does the MrTree algorithm have that are not present in the layered algorithm?

**Comment by pranithasri** [comment]
I am using MrTree for Hierarchical rendering of nodes .It is missing in some cases in layered algorithm

**Comment by soerendomroes** [comment]
Can you provide an example of this? I would like to solve a potential bug.

**Comment by pranithasri** [comment]
Here is an example of looping connection in [sandbox](https://codesandbox.io/embed/priceless-chandrasekhar-hysinf?fontsize=14&hidenavigation=1&theme=dark) n4 is the node connected in loop to n1.Here n4 should be child to n1 in my use case which is not happening in layered algorithm but able to achieve it in Mr tree

**Comment by soerendomroes** [comment]
If I understand correctly then you want to have control over the cycle breaking phase of the algorithm, meaning you want to decide which edges are reversed. One already existing way to do this is [constraints](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMaA3kWsxtnjKWAHSa5QDCEUgGc4UYBzjoAYgEkASgGUAKkxaYARjhBoARLV1EAvmQpVSAJgZrmm7XsuGT5StQDM1lqy079bp6aupAAsnurAPg7BAYRg5nQAtAB81BZEsfFoye7pBHHUiSkhufkhWUU0QA). With the next release you should also do cycle breaking by the model order. This means that in this example `n1` will be put in the first layer since it is the first node in the model and, therefore, all incoming edges of `n1` are considered to be backward edges.

**Comment by soerendomroes** [comment]
Other solutions are also stated [here](https://github.com/eclipse/elk/issues/786).

**Comment by pranithasri** [comment]
Thank you so much @soerendomroes for quick replies.I can use Mr tree for now.But only my concern with Mr tree is  ordering of child nodes in the order of ports position in source node.Can you please suggest me any possible solution for this use case

**Comment by soerendomroes** [comment]
This is not possible with MrTree. We had a student thesis regarding that a while ago but it was never revisited and added to the master.

**Comment by soerendomroes** [comment]
It might be a bit less convenient but the following solution also works if you do not want to constrain long edges:
```
algorithm: layered
elk.direction: RIGHT
crossingMinimization.semiInteractive: true
cycleBreaking.strategy: INTERACTIVE
layering.strategy: INTERACTIVE
node n1 {
    layout [position: 0, 0]
    label "n1"
}
node n2{
    layout [position: 100, 0]
    label "n2"
}
node n3{
    layout [position: 200, 0]
    label "n3"
}
edge n1 -> n2
edge n1 -> n3
```
