### ISSUE TITLE
[Question] Need some help with `layered` layout options

### ISSUE THREAD

**Issue by snelsi** [kieler/elkjs#259]
## ⭐ Thanks for the amazing library!

I'm currently working with the `elkjs` in my project, and I'm having a hard time understanding the extensive list of parameters in the documentation. If someone has experience with elk params, could you please help me to configure `layoutOptions` for my use case? Any help is greatly appreciated.

## Design I'm trying to achieve
I'm trying to achieve a layout that looks something like this:
![image](https://github.com/kieler/elkjs/assets/15171036/5aa1a729-7fa8-4a41-86ac-fe4a725d9c2d)
![image](https://github.com/kieler/elkjs/assets/15171036/e78b0772-9152-428f-b0f5-d61f7472169a)

Layered vertical/horizontal hierarchical view with smoothStep edges.

## How it looks at the moment
I'm using `layered` algorithm.
But the closest result I was able to achieve still has some issues:

![image](https://github.com/kieler/elkjs/assets/15171036/e0d00bf2-b581-4035-8478-3bf277252808)

- Edges on the bottom aren't straight,
- And I'm seeing a lot of edges overlapping over nodes.

## My current layoutOptions config

My `layoutOptions` config looks something like this:

![image](https://github.com/kieler/elkjs/assets/15171036/5a41069b-6a3c-4b68-a0cf-1c49f6b17ac7)

I suspect that it has a lot of unused/useless params since I copy-pasted them from other Github tickets. 

Also, is there a way to tell elk that my edges can only bend in the middle? 

Thanks for any help in advance 🙏

**Comment by soerendomroes** [comment]
I suggest to build example models in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html) or [elklive json](https://rtsys.informatik.uni-kiel.de/elklive/json.html). Otherwise, I am having a hard time seeing what you are actually configuring and whether this is a problem of ELK or on your side. Moreover, I can copy and paste stuff and try it out. If I just have a picture, I have to spend a considerable amount of time recreating it and often cannot reproduce the issue.

If you chose the layered algorithm, you can potentially use [all options for it](https://eclipse.dev/elk/reference/algorithms/org-eclipse-elk-layered.html).
In your layout config, it does therefore not do anything to include "elk.graphviz.concentrate".
Some of these options however belong to different strategies and can only be used when they are active, which can be seen in their naming scheme.
E.g., since you are using the `nodePlacement.strategy` `LINEAR_SEGMENTS`, everything with the path `nodePlacement.bk...` will not have an effect (bk stands for Brandes & Köpf node placement).

My answer would be that your layout does not look like a problem ELK should currently have and it might have something to do with a configuration that is not the one you showed here but I would need your actual graph to confirm anything.

My question is whether your graph is actually a tree. If this is the case, have you considered using the [`mrtree` algorithm](https://eclipse.dev/elk/reference/algorithms/org-eclipse-elk-mrtree.html)?
If this not the case, I have a student who is currently working on a node placement algorithm to implement a more balanced layout.

**Comment by snelsi** [comment]
@soerendomroes 

Here's `elklive.json` data file with the most complicated graph I have 👇
[elklive.json](https://github.com/kieler/elkjs/files/14039520/elklive.json)

Looks something like this on my side:
![image](https://github.com/kieler/elkjs/assets/15171036/f9b1a95a-96e7-4e5c-850d-58cedd60a8f1)

**Comment by soerendomroes** [comment]
Thanks for investigating. In that case, I guess it might have to do with labels that contribute to the node size in the example above.

PS: elklive has a button on the bottom left to share the link to your model.

**Comment by snelsi** [comment]
My example is too big to be embeded in a link. 😅
Share link just crashes if I try to open it

**Comment by soerendomroes** [comment]
Maybe a small example that reproduces the issue would suffice?

**Comment by snelsi** [comment]
I just need a recommendation for what `layoutOptions` to use to achieve the best results for my case.
Based on the data and design reference.
Especially from someone who understands what different layout options there are and what do they do.

**Comment by soerendomroes** [comment]
Try using [`considerModelOrder.strategy: PREFER_EDGES`](https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-considerModelOrder-strategy.html) and use the [default node placement strategy](https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-nodePlacement-strategy.html) with [`bk.fixedAlignment: BALANCED`](https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-nodePlacement-bk-fixedAlignment.html).

**Comment by soerendomroes** [comment]
mergeEdges and the spacings also look good if you want that option values.
