### ISSUE TITLE
Layout configurations not applying

### ISSUE THREAD

**Issue by manansoni77** [kieler/elkjs#283]
Hi,
I am using the elkjs library for the first time to create a graph. I am using the layered algorithms and trying to apply some additional configurations to it, but the configurations are not working, i.e they are not having any effect on the graph.

```js
const elkOptions = {
        // 'elk.algorithm': 'mrtree',
        'elk.layered.spacing.nodeNodeBetweenLayers': '100',
        'elk.spacing.nodeNode': '80',
        // new options
        'elk.layered.nodePlacement.strategy': 'NETWORK_SIMPLEX',
        'elk.layered.crossingMinimization.semiInteractive': 'True',
        'elk.separateConnectedComponents': 'False',
        'elk.contentAlignment': 'V_TOP'
};
const graph = {
	id: 'root',
	layoutOptions: options,
	children: nodes.map((node) => ({
		...node,
		// Adjust the target and source handle positions based on the layout
		// direction.
		targetPosition: isHorizontal ? Position.Left : Position.Top,
		sourcePosition: isHorizontal ? Position.Right : Position.Bottom,

		// Hardcode a width and height for elk to use when layouting.
		width: 150,
		height: 50
	})),
	edges: edges
};
elk.layout(graph)
```

Without new options
![image](https://github.com/kieler/elkjs/assets/64540033/f19f4629-955b-4329-adec-939b5aa8eade)

With new options
![image](https://github.com/kieler/elkjs/assets/64540033/bbcd2b56-8bc4-45d8-bc0a-f4bcaaf392f9)

Both are exactly the same, which leads me to believe that layout options are not working.

* elk version - "elkjs": "^0.9.3"

Please help regarding how to apply configurations correctly.

**Comment by soerendomroes** [comment]
This may be a typo: you declare `elkOptions` but use `options` in your graph. I am not sure whether you should use `true` and `false` instead of `True` and `False`. 

Have you tried creating a graph in elklive?

At least to my understanding, only `elk.layered.nodePlacement.strategy': 'NETWORK_SIMPLEX` could actually affect your graph. `semiInteractive` needs positions of elements (which might not be there), you only have one connected component, and I am not sure whether `contentAlignment` would work as you want it on the root and whether you need an additional horizontal option for it to work.

**Comment by soerendomroes** [comment]
And for `elk.layered.nodePlacement.strategy': 'NETWORK_SIMPLEX'` the drawings seem to be slightly different.

What exactly are you trying to achieve for your drawing?

**Comment by manansoni77** [comment]
Hey @soerendomroes 

The elkOptions typo is not the problem, it's just snippets of the whole code so it is like that.
As for what I'm trying to achieve is something like this (below)

![image](https://github.com/kieler/elkjs/assets/64540033/7cdf9dc3-c261-442d-bc73-5cad5a0e00d7)

Also, i tried a few examples from elk demonstrators, and [this](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=general/spacing/nodesEdges) was the one I was trying to reproduce when I ran into the issue of elkOptions not having any effect. It is not exactly like my goal, but atleast it had all the nodes and edges clearly seperated and not overlapping.

**Comment by soerendomroes** [comment]
Overlaps should not be created by ELK if you configure the node sizes as they actually are.

Maybe something similar to [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAHYQE4AKmAxjkjiXAHQDOcUwcOYW6AcgFEAKgHUA8gCUA0gH0AygEkAspQAyggBpEaEEqxgUoy8jhDioRthy48+afuIAig+bICC-J7MFOA4q5EpKZoJACMaADeRGixoabyMABeOMy6+jYwTKwCzoKyau4AQoJq8jFxZBRqwABGZqzMAA609Ixw6ABEivxKLmgAarIAwoL8woKSaAASI2MTkp0VsZj1IGidOABu7WhhSwC+wRShAExRy-EUiSlpeuycWXA5DnkFxaXlcVc4NWuNLWAdAYTC6PT6gkGc3Gkxm0IWS2+qzMG22u1Oh2OOFCAGYLt8qjgbql0g9gE8Xo4XO8SmVLoS-g1mq0QR0NuDFP0hqMYVNZjyEZdketNjsmGgcZjCaEACz4yoJZIk+6ZbK5amFWlfBXVOpMwHA9pg3qcyHc+aw-kWxZCvUitHimVSkIkACs8tihOJdwyjzVrw1HzpBNMjJAAJZRvZJq58MtcZtSLtqLFcDQrudJxIADYPT9vaTVc91flNZ96aG7RGgW1QdGIVCBfGm4m4sKU7ts5igtLwhFoiHrkqfWSKSWaeXB78q8ya6zjQ3zby4S3EW3k50kMB2Hg0DQEMAmtwoHs17EmtA01kiEcsaEAOx5r3Dwt+4sB0tB7Weyv-WeGutuhjM0ExXa0zwwDcHTTe9MUIMBsRIOUAFoAD5QjCMJmGveDEPdNCMKwnCCAQ0JcwIvtsJIIJcIwtCSHOAc4iaWBoHgLBrEeMAEDgEgcFYF4wgABiEm8iFohj6LxJjz1Y2A4A40duN4-jBJEsSJJxei5RktAWJgNiFM48llL4gT0GE0SjgkmV6PdXT9MMxTMlM1SLPU6ySLw+jcwcuT2OMmBXPMvYPPEryyPox8-IM+TnK4nizLUqygjvEgAA4n0VW5X3Jf0qU-LUK11P8DVrNkgMXUCrV5CD203bdjzQABHABXfi4AM-RTw0iLwjQCj0p7F0AE5dOfHKVTfSk3jLYMdWnUrI0AjlYxbMDattNYNi3HcT2AfQAHdd32MS0uErKh0m308vfAqJ3mn8Sv1ZaKtWkD1pqwUk22hq9rQA7WGOk8MV60iMoG9CSBG8LwcyijhKCIA) might work for you. I used network simplex for node placement and straightness priority for edges that should be straight. Additionally you might want to use explizit ports with fixed positions.

What framework are you using? In the last year, we had similar overlap problems from people that used reactflow for their diagrams.

**Comment by manansoni77** [comment]
I am using [svelte-flow](https://svelteflow.dev/) framework.

I'll try the demonstration you have suggested.

**Comment by manansoni77** [comment]
Hey @soerendomroes , I tried applying the properties like those [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAHYQE4AKmAxjkjiXAHQDOcUwcOYW6AcgFEAKgHUA8gCUA0gH0AygEkAspQAyggBpEaEEqxgUoy8jhDioRthy48+afuIAig+bICC-J7MFOA4q5EpKZoJACMaADeRGixoabyMABeOMy6+jYwTKwCzoKyau4AQoJq8jFxZBRqwABGZqzMAA609Ixw6ABEivxKLmgAarIAwoL8woKSaAASI2MTkp0VsZj1IGidOABu7WhhSwC+wRShAExRy-EUiSlpeuycWXA5DnkFxaXlcVc4NWuNLWAdAYTC6PT6gkGc3Gkxm0IWS2+qzMG22u1Oh2OOFCAGYLt8qjgbql0g9gE8Xo4XO8SmVLoS-g1mq0QR0NuDFP0hqMYVNZjyEZdketNjsmGgcZjCaEACz4yoJZIk+6ZbK5amFWlfBXVOpMwHA9pg3qcyHc+aw-kWxZCvUitHimVSkIkACs8tihOJdwyjzVrw1HzpBNMjJAAJZRvZJq58MtcZtSLtqLFcDQrudJxIADYPT9vaTVc91flNZ96aG7RGgW1QdGIVCBfGm4m4sKU7ts5igtLwhFoiHrkqfWSKSWaeXB78q8ya6zjQ3zby4S3EW3k50kMB2Hg0DQEMAmtwoHs17EmtA01kiEcsaEAOx5r3Dwt+4sB0tB7Weyv-WeGutuhjM0ExXa0zwwDcHTTe9MUIMBsRIOUAFoAD5QjCMJmGveDEPdNCMKwnCCAQ0JcwIvtsJIIJcIwtCSHOAc4iaWBoHgLBrEeMAEDgEgcFYF4wgABiEm8iFohj6LxJjz1Y2A4A40duN4-jBJEsSJJxei5RktAWJgNiFM48llL4gT0GE0SjgkmV6PdXT9MMxTMlM1SLPU6ySLw+jcwcuT2OMmBXPMvYPPEryyPox8-IM+TnK4nizLUqygjvEgAA4n0VW5X3Jf0qU-LUK11P8DVrNkgMXUCrV5CD203bdjzQABHABXfi4AM-RTw0iLwjQCj0p7F0AE5dOfHKVTfSk3jLYMdWnUrI0AjlYxbMDattNYNi3HcT2AfQAHdd32MS0uErKh0m308vfAqJ3mn8Sv1ZaKtWkD1pqwUk22hq9rQA7WGOk8MV60iMoG9CSBG8LwcyijhKCIA)

I tried various combinations and different ways to apply them as described below, but they made no difference.

* Add properties to nodes and edges
```js
node = {
        id: 'e1',
        type: 'custom',
        data: { label: 'event 1' },
        'nodeSize.constraints': 'NODE_LABELS',
        'elk.nodeSize.constraints': 'NODE_LABELS',
        'nodeLabels.placement': 'INSIDE V_CENTER H_CENTER',
        'elk.nodeLabels.placement': 'INSIDE V_CENTER H_CENTER',
        port: 'in',
        position
},
edge = {
        id: 'e1mq1',
        source: 'e1',
        'priority.straightness': 100,
        'elk.priority.straightness': 100,
        target: 'mq1',
        type: edgeType,
        animated: true
},
```

* Add properties to elkOptions
```js
const elkOptions = {
        'elk.algorithm': 'layered',
        'elk.layered.nodePlacement.strategy': 'NETWORK_SIMPLEX',
        'nodeSize.constraints': 'NODE_LABELS',
        'elk.nodeSize.constraints': 'NODE_LABELS',
        'nodeLabels.placement': 'INSIDE V_CENTER H_CENTER',
        'elk.nodeLabels.placement': 'INSIDE V_CENTER H_CENTER',
        'priority.straightness': 100,
        'elk.priority.straightness': 100
};
```

Either of these changes are not having any affect on the output graph.
![image](https://github.com/kieler/elkjs/assets/64540033/1ee1a331-428e-4e7e-984f-ae08e0d5c72f)

**Comment by soerendomroes** [comment]
Well, the drawing looks different. Maybe I did not fully understand what you are interested in.
How does your desired output look like?

The `priority.straightness` is applied like [this](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGBECWAmkC4oDsAMkA04oGMAW0ANrAE4CmyiYA2thKBI1HFZMgIyZ2OSECGAIzKEAzlVpMmDSU0gAXMgA85rMgDcKcsJ25MAvrrABdLDMgB3OHLxUAHKgB0qU5Mh4y0AOZ4VSAMyOqNx6LvSGMPBIbABMXGb8QqLihmEysgrKqhrIWrEpYAYyJuGWsNZ2gaE87l4+VAFOwVXSsixRyH5xrgnCYkgSaS1p8kq+UOqaYJ35hZLFZqXlSPZOVRBuHt5jDUH6zeFtKAAsXbI9Sf35Q2YZY5ATOWAnM4bzros2y5XhNVv1gU1uNdmJEUABWU48c59GhXfLrW5ZSYQl5FNZQD4VVY-TZ1fwAvZAg6gtgANkh62hyTSYGB6VGSMe5NRc3RFisnzAK2cONq2wJjBCRLMhzY7E4bKplxpdJ4iKiAFs+CIFCQwPg+AAHVXaSAsphvWSagD2JDkMIGMll61F0Eo+sYhp4mK+2LMvzxUwFECFUmJrGQAHYKVApbCZfCoPLxtktMGHRAnesXVzvu7cfzGoS-SKSchbCHeIJetTBpGRplFcqdQBHACuZBV0GNyBEuoTxjZKe5bI9md2gv2uYDAE5C2HLZJrVGGVWVWQ1XxW+YF+2abMDV2OVieem+f8s4Pha5RRx0JLixdw2WaQjZ1AlfPF8vV3l168t2VOT3eX98YefWwN4iwAT2NOs5AAeW1ZtWyoIZID4QhPFNaBrAVVh+BAhcyHgKo2GNWAyAABX4HAyAVTQHBVEg+AUTwQNYAA5ABRAAVAB1SCACUAGkAH0AGUAEkAFliIAGRYgANSFIBwFsRDgBdRMI4RIJIIiSGouRaPoxioiYyCABEWME-iAEEmOM-iWOMgBxMy9R9Fx7lgTxG1LVITxJMhz3CERwJIciLXyNhnjRcI5D4EgPPNLyT3tIpARzHzVAlAKgpChLZGQFFIpuGK4tCmkYCSuYUsYYEIlUWI2UCutgs86VhmQZkCtcaLYrIeKWpFcqDUq7zWl8zp6qy5rrzMDhnNZKKip6krWrfOb4j4MCIOguRYJhWVIE1Ehm0OuQQJ02i+WQRsYUgdhUHQQwNwKIc0qiMgTnGxrsr61xkBWzd5u63qpp+6YOrOdbwKgmDFPgsKDqOtDTpovgLqu1hbvumRHt9Kr-VeiEPqapbptB1bOoWoHJ1yiKyfBjaoe2mGkD2+HUJOs6Ua2S6RGujHZv0IbaTx8ZyUJr7gep-nHTZLripyng8qlxML3pradth0rWeOpHdM5nxud5u6lYKQXqtFMhgzFyaqYV-LablCniZ+9r7cpCHNuhuDmbhw62Z186ubRqI+Ye03hfuAsrad3KXf+wrAejhX4zBqF3YZ9Xvc133tY51GefRo3Q+zXHh1esco-l9YZo-AG5e+3KC1eMPS-GW7CwaonK5QRuU4RR2u7YMcm+L4aeHN8V24mxOq5712o37+uFbb4fBSAkA9CAA) to a json graph. More documentation can be found [here](https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-priority-straightness.html). Since it applies to edges, you can set it on individual edges. If it applied to `parents`, you would add the property to the root node as it is the case for e.g. [`cycleBreaking.strategy`](https://eclipse.dev/elk/reference/options/org-eclipse-elk-layered-cycleBreaking-strategy.html).
