### ISSUE TITLE
Node placement issue

### ISSUE THREAD

**Issue by Abhishek-Shandilya** [kieler/elkjs#306]
Hi, i have a drag and drop workflow where i am creating a loop.

Reproduction in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=KYGw1gdAhiDmD2AnAlgFwBYFsBcACEUAnsIsACYBQokZypAxqsvAHZ4AiA8gOoByV4aCGSwWmYC1R4AwgFFeAFVkAlAZADOAByj1kLWBBbwywXseB4AjABYADGohadeg-XiZNrCamnvPLbzwANntqCAJiUjJHbV19CAAjKHVgADUYAFcLXAAOUMEIknJDcwAFAnpgcUlHVEQoVGBYQjxeWQVuTmUAaQB9AGUASQBZUoAZWQANB0KoiHpEeHV1F2G9ZExkAC8G5hZa+sbmvDGAQQBNFQHuWVlSmaIi6LcWFZNEYfMQTkR3g4ami1cLxOG0HNpEEwmKwXNBGMgAG4AvB1LIOciwYDKeAZJj6PBdBQACU4AHFQacxhQAPTU3BhJxxAx6WgI5BkDIwfrAVB42DqFGINEM2KwjGmcxWABM+Q0ovi4tkZExwVlEHQyBIUEQ9HQhCJUBYZGE+Nwg140jGAFV2LJetIiYMxuxlPIHC9GpJTsJRNUpLgifb5EpVLT6YIjCYxlAEqB1BBNBUqoEzbwhrbcKkg4oVAHsyGaXSwrNiuJEJilZiBbgAGYwFKF8OQcUxE3Aauo4AUCiR4C4Fi2ADeFFwo-wMdAuAAROpUNrUFOKABfHvmfuWXDDsfj2MgacgeDwTS4Wfzxcr3v9qWbkdjgi76fAJEgTmoJDn1cmfsAZhv2-vk5Tp29IeKghD9uYH6Xiw1hbneE57lOdYgCkIGaGBEEmFBa4sAArH+8EPlOZaYphwDYV+LBBARo4AYhB5HvSRoUX2LAAOw0TugESGQH7iv2ti4AAtAAfOuVDKqxG6iVeEmkSw0liVRcmsdRMkKSpV7CUp36aSw17qdYem-upuF6dY2n9mZ-F4ZZyk2WpSlsUAA).

**Expected behavior**
Evaluator Node and its children should be between entry and exit.

**Screenshots**
When i add evaluator node with its children this happens.
This doesnt work:
![image](https://github.com/user-attachments/assets/10094427-aef3-4754-8807-c0a8daec59bc)

But when a single node is added it works correctly.
This works:
![image](https://github.com/user-attachments/assets/41ef6e3a-d588-43cf-b2b4-3629249e4f21)

i would like to know what is the issue here and how to fix it.

layoutOptions used:

```
'elk.algorithm': 'layered',
'elk.direction': 'DOWN',
'elk.alignment': 'CENTER',
'elk.spacing.nodeNode': '140',
'elk.spacing.componentComponent': '60',
'elk.layered.spacing.baseValue': '80',
'elk.layered.nodePlacement.strategy': 'NETWORK_SIMPLEX',
'elk.layered.crossingMinimization.strategy': 'LAYER_SWEEP',
'elk.layered.considerModelOrder.strategy': 'NONE',
'elk.partitioning.activate': 'true',
'elk.edgeRouting': 'ORTHOGONAL',
'elk.spacing.individualSettings': 'true',
'elk.spacing.edgeNode': '120',
'elk.spacing.edgeEdge': '60',
'elk.hierarchyHandling': 'INCLUDE_CHILDREN',
'elk.contentAlignment': 'H_CENTER',
'elk.nodeLabels.placement': 'INSIDE V_CENTER H_CENTER',
'elk.layered.mergeEdges': 'true',
'elk.edge.splines': 'true',
```

**Comment by soerendomroes** [comment]
Hi, I must guess what is wrong, since you did not reproduce the issue in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html).

It might depend on the cycleBreaking strategy you are using and potentially on the partitions you might set. Maybe try setting the `cycleBreaking.strategy` to either `GREEDY_MODEL_ORDER` or to `DEPTH_FIRST`. If this does not solve the issue, I would like you to reproduce your problem in elklive.

**Comment by Abhishek-Shandilya** [comment]
Hi, thanks for the quick reply.

Reproduction in [elklive](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=KYGw1gdAhiDmD2AnAlgFwBYFsBcACEUAnsIsACYBQokZypAxqsvAHZ4AiA8gOoByV4aCGSwWmYC1R4AwgFFeAFVkAlAZADOAByj1kLWBBbwywXseB4AjABYADGohadeg-XiZNrCamnvPLbzwANntqCAJiUjJHbV19CAAjKHVgADUYAFcLXAAOUMEIknJDcwAFAnpgcUlHVEQoVGBYQjxeWQVuTmUAaQB9AGUASQBZUoAZWQANB0KoiHpEeHV1F2G9ZExkAC8G5hZa+sbmvDGAQQBNFQHuWVlSmaIi6LcWFZNEYfMQTkR3g4ami1cLxOG0HNpEEwmKwXNBGMgAG4AvB1LIOciwYDKeAZJj6PBdBQACU4AHFQacxhQAPTU3BhJxxAx6WgI5BkDIwfrAVB42DqFGINEM2KwjGmcxWABM+Q0ovi4tkZExwVlEHQyBIUEQ9HQhCJUBYZGE+Nwg140jGAFV2LJetIiYMxuxlPIHC9GpJTsJRNUpLgifb5EpVLT6YIjCYxlAEqB1BBNBUqoEzbwhrbcKkg4oVAHsyGHpFiuJEJilZiBbhUcAaXSwuKYibgJXqxQKJHgLgWJZcABvCi4Qf4GOgXAAIhA8Hgmlw6lQ2tQY4oAF92+Yu1K+wOhwRYyBx8AkSBOagkEvVx2uwBmLdD4d78fV+keVCELvmc9rkxd6z9u+70cxwAMxgFJn00V93xMT9LxYABWW8dxHfcxxLTEoOAGD1xYIJEMHACUMnad6SNT8qGVTtu1wABaAA+DdyPQqi6K7IJGMo3CWO7diNxo+iWCvHiWE3LjrCEm8uLgoTrD4rspPFOTZJwoA).

**Comment by soerendomroes** [comment]
[Here](https://rtsys.informatik.uni-kiel.de/elklive/examples.html) are a few examples for some use cases.
Otherwise, all layout options of the layered algorithm are documented [here](https://eclipse.dev/elk/reference/algorithms/org-eclipse-elk-layered.html).
In terms of order in your drawing, I recommend reading [this](https://eclipse.dev/elk/blog/posts/2023/23-01-09-constraining-the-model.html) blogpost.
What exactly is all of this for you?

Is [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=KYGw1gdAhiDmD2AnAlgFwBYFsBcACEUAnsIsACYBQokZypAxqsvAHZ4AiA8gOoByV4aCGSwWmYC1R4AwgFFeAFVkAlAZADOAByj1kLWBBbwywXseB4AjABYADGohadeg-XiZNrCamnvPLbzwANntqCAJiUjJHbV19CAAjKHVgADUYAFcLXAAOUMEIknJDcwAFAnpgcUlHVEQoVGBYQjxeWQVuTmUAaQB9AGUASQBZUoAZWQANB0KoiHpEeHV1F2G9ZExkAC8G5hZa+sbmvDGAQQBNFQHuWVlSmaIi6LcWFZNEYfMQTkR3g4ami1cLxOG0HNpEEwmKwXNBGMgAG4AvB1LIOciwYDKeAZJj6PBdBQACU4AHFQacxhQAPTU3BhJxxAx6WgI5BkDIwfrAVB42DqFGINEM2KwjGmcxWABM+Q0ovi4tkZExwVlEHQyBIUEQ9HQhCJUBYZGE+Nwg140jGAFV2LJetIiYMxuxlPIHC9GpJTsJRNUpLgifb5EpVLT6YIjCYxlAEqB1BBNBUqoEzbwhrbcKkg4oVAHsyGaXSwrNiuJEJilZiBbgAGYwFKF8OQcUxE3Aauo4AUeiEeggYAAIVIUDAsPUdQBx1wttKxN6ADFBsp+goKBRI8BcCxbABvCi4A-4GOgXAAInH2tQp4oAF91+Yt5ZcHvD7hPJDfK8J3pUNXF5NZHYAZBltfdDwIWMQDPEB4HgTRcAvSFrzAg931QXAAHd23Ql9X0PAA9NDHHZbIbhXFDcDvCi0PpZIcIo19CKQVBiJMPBZFOcjXzvO8Ny3KVnwoiCT1PYAkRATlUCQa9eIfFgAGZBNfYSoNPTt6Q8VBCC3cwZPvEwt2sXCDxUs86xAFINM0LSdJMPS+JYABWJTwOPVSy0xWzgHsuSghc1DmM-cd6h-P9BgAoD01kIS3Og2D4IkMhkNfGisPHfy8KYyFWNI2QuMPKiUuY2j0uMzKiLebIOPyg8eP0zcWAAdgy0zRKNPTxS3WxcAAWgAPkfKhlQap9+v4obPJYSwIGAOjeoGlgghmuiJoapa0vQsapogDbVv4+at3kvaWAErbrGOxStsc47rAOpzjucragmOvytsaoA) what you want to achieve?

**Comment by Abhishek-Shandilya** [comment]
>What exactly is all of this for you?
I don't understand the question.

> Is [this](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=KYGw1gdAhiDmD2AnAlgFwBYFsBcACEUAnsIsACYBQokZypAxqsvAHZ4AiA8gOoByV4aCGSwWmYC1R4AwgFFeAFVkAlAZADOAByj1kLWBBbwywXseB4AjABYADGohadeg-XiZNrCamnvPLbzwANntqCAJiUjJHbV19CAAjKHVgADUYAFcLXAAOUMEIknJDcwAFAnpgcUlHVEQoVGBYQjxeWQVuTmUAaQB9AGUASQBZUoAZWQANB0KoiHpEeHV1F2G9ZExkAC8G5hZa+sbmvDGAQQBNFQHuWVlSmaIi6LcWFZNEYfMQTkR3g4ami1cLxOG0HNpEEwmKwXNBGMgAG4AvB1LIOciwYDKeAZJj6PBdBQACU4AHFQacxhQAPTU3BhJxxAx6WgI5BkDIwfrAVB42DqFGINEM2KwjGmcxWABM+Q0ovi4tkZExwVlEHQyBIUEQ9HQhCJUBYZGE+Nwg140jGAFV2LJetIiYMxuxlPIHC9GpJTsJRNUpLgifb5EpVLT6YIjCYxlAEqB1BBNBUqoEzbwhrbcKkg4oVAHsyGaXSwrNiuJEJilZiBbgAGYwFKF8OQcUxE3Aauo4AUeiEeggYAAIVIUDAsPUdQBx1wttKxN6ADFBsp+goKBRI8BcCxbABvCi4A-4GOgXAAInH2tQp4oAF91+Yt5ZcHvD7hPJDfK8J3pUNXF5NZHYAZBltfdDwIWMQDPEB4HgTRcAvSFrzAg931QXAAHd23Ql9X0PAA9NDHHZbIbhXFDcDvCi0PpZIcIo19CKQVBiJMPBZFOcjXzvO8Ny3KVnwoiCT1PYAkRATlUCQa9eIfFgAGZBNfYSoNPTt6Q8VBCC3cwZPvEwt2sXCDxUs86xAFINM0LSdJMPS+JYABWJTwOPVSy0xWzgHsuSghc1DmM-cd6h-P9BgAoD01kIS3Og2D4IkMhkNfGisPHfy8KYyFWNI2QuMPKiUuY2j0uMzKiLebIOPyg8eP0zcWAAdgy0zRKNPTxS3WxcAAWgAPkfKhlQap9+v4obPJYSwIGAOjeoGlgghmuiJoapa0vQsapogDbVv4+at3kvaWAErbrGOxStsc47rAOpzjucragmOvytsaoA) what you want to achieve?

Yes, currently there are some spacing issues, ill try to look into them on my own.

**Comment by soerendomroes** [comment]
> Yes, but currently there are some spacing issues.
> 
> I don't want to keep asking as the original node placement issue is resolved but can you suggest how to fix this spacing.

Yes, the issues is that the rendering of your nodes does not match the size that ELK thinks your nodes have. Hence, if your nodes have a fixed rendering size, you should add this as a `nodeSize.minimum` and add `MINIMUM_SIZE` to your `nodeSize.constraints.

**Comment by soerendomroes** [comment]
> I don't understand the question.

You stated "Is there any documentation i could read to learn about all of this, which is easy to approach."
To answer that I need to know more specifically what you mean by "all of this".

**Comment by Abhishek-Shandilya** [comment]
I'll try adding adding a minimum size to all nodes.

And by `all of this` i meant layoutOptions, to create my own understanding of how its working and how can i manipulate it, The elk documentation & reference material does provide all the options but lacks in examples differentiating between the options. The examples page provides some use-cases.

What my initial question was:
`An easy to approach documentation or guideline to build graphs with elk which could help me solve my questions.`

**Comment by Abhishek-Shandilya** [comment]
This is my layoutOptions for a single node:
```{
                    'nodeSize.constraints': "MINIMUM_SIZE",
                    'nodeSize.minimum': `(${width}, ${height})`
 }```
 
 This doesnt solve the edge-node overlapping issue though.
 
 if i increase the width or height by adding some padding this happens:
![image](https://github.com/user-attachments/assets/28d1ab65-33f8-4e9c-874a-2dfe61c3298f)
you can see a slight gap on the right side.

**Comment by Abhishek-Shandilya** [comment]
It appears that the minimum size is being correctly calculated by ELK and rendered accordingly, so no discrepancy is apparent there. On closer examination, the crossing line within the node aligns precisely with the node's padding. This observation suggests that ELK might not be accounting for padding in its layout calculations. I will conduct further tests focusing on padding configurations to confirm. It may be necessary to explicitly specify padding to ensure ELK incorporates it into the layout as intended.

**Comment by Abhishek-Shandilya** [comment]
i will be closing this issue as i think we have resolved the node placement issue.

Thanks again.
