### ISSUE TITLE
[Question] How to disable automatic wrapping?

### ISSUE THREAD

**Issue by mscandan** [kieler/elkjs#310]
**Ask your questions**
Hello, I am using ElkJS with ReactFlow.

I am using partitions to separate some nodes to a specific partition. When I add more nodes to a column, after some number of nodes it gets wrapped and creates a new column in the partition. I'd like to achieve only one column view. Do you have any tips on achieving this view?

I've created this [example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAA7BRzwwQB2MNYAdMAMaUBuwcO6cUArjiI4QAa0YEY+NtRroASgEkA4gAkAKsLGMAzjjJQuOAMK0aONoVNIStHDTg70AM1B6iRGhAI40NAIxoAN5EaGFoBpSUtPRMkVS06P6h4aCQsIioGNh4hClhIuKS0tFyaAAiAPIA6gBy+X7eviz+IeHt2QBGImgARC29DQC+DV4+aCwATG0dYZjdIH1Tg+0j7WPNAOwzs-M9-Zsr4WvhGxMAHDsde4v950dhJ2FnLACcV+03S68PaCMjniafkmwQa8VKsUY4Nk6EmoyBLAAzB9wl9+ojfk9GuMWAAWFFzYALJa4zFEAFnGiI0HtaExBhQ8hRGFoRHwnEAVgJXX2LA5ZPWCIAbNy0SwhWSAYQwL4AowWmgALQAPmB8rZ0tlk3VStVVPlHKAA)

**(Optional) Expected behavior**
I want every node in every partition to be in top to bottom order.

**(Optional) Screenshots**
Current State:
<img width="2362" alt="image" src="https://github.com/user-attachments/assets/9b23447e-d9dd-4d2d-9468-9bd00d7fbd2d">

Desired View:
<img width="1724" alt="image" src="https://github.com/user-attachments/assets/80a51d69-e9f2-41ef-8b68-76971b47746d">

View with setting `elk.hierarchyHandling` to `INCLUDE_CHILDREN`
<img width="1656" alt="image" src="https://github.com/user-attachments/assets/64bfccfc-f483-4ebe-afe3-082d5b210595">

**(Optional) ELK Version**
The ELK or elkjs version: v0.9.3

**Comment by Eddykasp** [comment]
The problem is that you are using layered for a graph with no edges so the nodes are layouted as separate components. One way you can achieve your goal is by using rectpacking and setting the aspect ratio to a suitable value (see [example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAA7BRzwwQB2MNYAdMAMaUBuwcO6cUArjiI4QAa0YEY+NtRroASgEkA4gAkAKsLGMAzjjJQuOAMK0aONoVNIStHDTg70AM1B6iRGhAI40NAIxoAN5EaGFoBpSUtPRMkVS06P6h4aCQsIioaNJwZCyisSlhwDokFnDyXNToAAyMAExFaCLikjmy6AAiAPIA6gByTV4+aCz+IeGTGMAARiJoAERjC00AvkPeviz1E1NhmHMgi9srk+uTw1sA7Lt7B-NLV6fh5+GXowAct1P3R0sfzzCrzC7xYAE5vpNfscwYC0Ot1p5Nn56sEmvFonQGIwMR00I0LsiWABmSHhaFLYlw4F+IkAFjJ+1mDxYdOpRER7xoxLRk1xMWx-LkaGJGxGLAArIzpodjhL2YTxQA2aUUlhK9mIwhgXwBRhjNAAWgAfCj9aLtbr6uajabufqJUA)).

Alternatively you could use layered, add edges, and make them invisible in the rendering.

**Comment by Eddykasp** [comment]
The `aspectRatio` appears to also work for layered so you don't need to use rectpacking.

**Comment by mscandan** [comment]
@Eddykasp thank you so much, my problem resolved with the `aspectRatio`
